spring:
  application:
    name: apr-2025-orderService
  datasource:
    url: jdbc:h2:./orderDB
    username: sa
    password:


  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 9595

eureka:
  client:
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/
