spring:
  application:
    name: java-apr-2025-spring-controller
  datasource:
    url: jdbc:h2:mem:appdb
    username: sa
    password:


  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8081
